eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8760
spring:
  application:
    name: ZUUL-SERVER
zuul:
  routes:
    api:
      path: /api/remote
      serviceId: SERVICE-SERVER

# 此处路由用的serviceId，则使用ribbon.ConnectTimeout配置超时
# 如使用url方式直连 则使用zuul.host.connect-timeout-millis， zuul.host.socket-timeout-millis配置超时
# ribbon和hystrix取小的那个
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
